### ISSUE TITLE
Can you add freezing (immobility) after teleporting? 

### ISSUE THREAD

**Issue by amadin** [shacknetisp/protection_lagporter#1]
Can you add freezing (immobility) after teleporting for a "check_time" time? Now if player was tried to dig protected block then he can't go away because player try go back, left or right but Lagporter teleport he again and again, sometimes player don't know about protection area and area owner so Lagporter must not irritate players.

**Comment by shacknetisp** [comment]
Done, I hadn't thought of doing it that way.
