### ISSUE TITLE
Mod permanent change player speed with "speed boots" 

### ISSUE THREAD

**Issue by amadin** [shacknetisp/protection_lagporter#2]
If player have speed boots created by enchant table (xdecor mod for examle) or crystal boots (with increased speed) from ehtereal and 3d_armor mods then protection_lagporter permanent change player's speed if player tried to dig protected block. So i think mod must remember player's speed before freeze and restore speed after disable freeze. Also sometimes after dig of protection block with gold pickaxe or diamond pickaxe player freezing forever. Maybe it makes sense just block player's keyboard or move and dig keyboard keys?

**Comment by shacknetisp** [comment]
This is impossible to do, you must change the boots mod to somehow detect `protection_lagporter.glitching[name]`, that is what I did for the sprint mod.

**Comment by shacknetisp** [comment]
> Also sometimes after dig of protection block with gold pickaxe or diamond pickaxe player freezing forever.

I think you need to get my latest change, I fixed a problem with that.

**Comment by amadin** [comment]
If i undestand right change speed of boots is because freezing. So there are no way to replace freezing by lock moving buttons and dig button or something else?

**Comment by shacknetisp** [comment]
The current change will lock speed to a very slow value, and I have tested that with the sprint mod and it works well.
Teleporting must be done continuously, because if there is a longer delay then the lag will allow the player to escape the teleporting and enter a protected area.

**Comment by amadin** [comment]
And last question - can you add to readme.md information about adding detect  protection_lagporter.glitching[name] for 3d_armor crystal boots for peoples who don't know lua good but have base knowledge about it? Or maybe developer of 3d_armor will add it itself if you tell him.

**Comment by shacknetisp** [comment]
Ok, added that section.

**Comment by shacknetisp** [comment]
And for 3d_armor specifically, find where the speed is increased or decreased, and multiply it by 0 if protection_lagporter.glitching[name] is true.
