### ISSUE TITLE
Lagporter don't work with new code from readme

### ISSUE THREAD

**Issue by amadin** [shacknetisp/protection_lagporter#4]
Lagporter don't work with new code from readme. Are you test it before?

**Comment by shacknetisp** [comment]
I have added generic examples, with instructions on how to add it to any protection mod's code.

**Comment by shacknetisp** [comment]
For TenPlus1's specifically:

Replace: `function minetest.is_protected(pos, digger)` with:
 `function minetest.is_protected(pos, digger, digging)`

And replace `if not protector.can_dig(protector.radius, pos, digger, false, 1) then` with:

```
if not protector.can_dig(protector.radius, pos, digger, false, 1) then
    if digging then protection_lagporter.check(pos, digger) end
```

**Comment by amadin** [comment]
Maybe you ask to Tenplus1 add this mod to protector-redo?
